In [1]:
squares=[1,4,9,16,36]
print(squares)

[1, 4, 9, 16, 36]


In [2]:
squares[0]

1

In [3]:
squares[-1]

36

In [4]:
squares[-1:]

[36]

In [5]:
squares[:1]

[1]

In [6]:
squares[:3]

[1, 4, 9]

In [7]:
squares[:4]

[1, 4, 9, 16]

In [8]:
squares[4:]

[36]

In [9]:
squares[:]

[1, 4, 9, 16, 36]

In [10]:
squares + [49,64,81,100]
print(squares)

[1, 4, 9, 16, 36]


In [12]:
squares+=[49,64,81,100]

In [13]:
squares

[1, 4, 9, 16, 36, 49, 64, 81, 100]

In [14]:
a=100
a+=1
print(a)

101


In [15]:
cubes=[1,8,27,65,125]
4 ** 3
cubes[3]=64
cubes

[1, 8, 27, 64, 125]

In [16]:
cubes.append(216)
cubes.append(7 ** 3)
cubes

[1, 8, 27, 64, 125, 216, 343]

In [17]:
letters=['a','b','c','d','e','f','g']

In [18]:
len(letters)

7

In [20]:
edward=['edward gumby',42]
john=['john smith',50]
database=[edward,john]
database


[['edward gumby', 42], ['john smith', 50]]

In [23]:
so=['social',78]
sc=['science',60]
sub=[so,sc]
sub

[['social', 78], ['science', 60]]

In [24]:
a=['a','b','c']
n=[1,2,3]
x=[a,n]
x

[['a', 'b', 'c'], [1, 2, 3]]

In [25]:
x[0]

['a', 'b', 'c']

In [26]:
x[1]

[1, 2, 3]

In [27]:
x[0][2]

'c'

In [29]:
numbers=[1,2,3,4,5,6,7,8,9]
numbers[0:10:1]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
numbers[0:10:2]

[1, 3, 5, 7, 9]

In [31]:
numbers[3:6:3]

[4]

In [32]:
numbers[2:5]

[3, 4, 5]

In [33]:
numbers[2:5:2]

[3, 5]

In [34]:
numbers[::4]

[1, 5, 9]

In [35]:
numbers[8:3:-1]

[9, 8, 7, 6, 5]

In [36]:
numbers[3:6]

[4, 5, 6]

In [37]:
numbers[7:10]

[8, 9]

In [38]:
numbers[-3:]

[7, 8, 9]

In [39]:
numbers[3:6]

[4, 5, 6]

In [40]:
numbers[0:1]

[1]

In [41]:
numbers[7:10]

[8, 9]

In [42]:
numbers[6:10]

[7, 8, 9]

In [44]:
numbers[-3:-1]

[7, 8]

In [45]:
numbers[-3:0]

[]

In [46]:
numbers[-3:]

[7, 8, 9]

In [47]:
numbers[:3]

[1, 2, 3]

In [48]:
numbers[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [50]:
'hello,'+'world'

'hello,world'

In [51]:
'python'*5

'pythonpythonpythonpythonpython'

In [52]:
['python']*5

['python', 'python', 'python', 'python', 'python']

In [53]:
[42]*10

[42, 42, 42, 42, 42, 42, 42, 42, 42, 42]

In [54]:
42 * 10

420

In [55]:
permissions='rw'

In [56]:
'w' in permissions

True

In [57]:
"s" in permissions

False

In [58]:
users=['anu','raj','foo','bar']
input("enter user name:")

enter user name:anu


'anu'

In [59]:
subjects='$$$ get rich now!!!$$$'

In [61]:
'$$$'in subjects

True

In [63]:
database=['alu','1234'],['tillu','4567']
username=input('user namr:')
pin=input('pin code:')

user namr:alu
pin code:1243


In [64]:
numbers=[100,34,6,78,34]
len(numbers)

5

In [65]:
max(numbers)

100

In [66]:
min(numbers)

6

In [67]:
list('hello')

['h', 'e', 'l', 'l', 'o']

In [68]:
x=[1,1,1]
x[1]=2

In [69]:
x

[1, 2, 1]

In [72]:
names=['ali','alan','celia','eagrl']

In [73]:
del names[2]

In [74]:
names

['ali', 'alan', 'eagrl']

In [75]:
name=list('perl')

In [76]:
name

['p', 'e', 'r', 'l']

In [77]:
name[2:]=list("ar")

In [78]:
name

['p', 'e', 'a', 'r']

In [84]:
name=list('perl')
name


['p', 'e', 'r', 'l']

In [1]:
name=list('perl')
name[1:]=list('ython')
name

['p', 'y', 't', 'h', 'o', 'n']

In [3]:
numbers=[1,5]
numbers[1:1]=[2,3,4]
numbers

[1, 2, 3, 4, 5]

In [4]:
numbers[1:4]=[]

In [5]:
numbers

[1, 5]

In [6]:
list=[1,2,3]
list.append(4)
list

[1, 2, 3, 4]

In [8]:
x=[[1,2],1,1,[2,1,[1,2]]]

In [9]:
x.count(2)

0

In [10]:
x.count([1,1])

0

In [11]:
x.count([1,2])

1

In [12]:
x.count(1)

2

In [13]:
a=[1,2,3]
b=[4,5,6]
a.extend(b)
a

[1, 2, 3, 4, 5, 6]

In [14]:
a=[1,2,3]
a+b

[1, 2, 3, 4, 5, 6]

In [15]:
a

[1, 2, 3]

In [16]:
lst=[1,2,3]
lst.clear()
lst

[]

In [17]:
a=[1,2,3]
b=a

In [18]:
b

[1, 2, 3]

In [19]:
b[1]=4

In [20]:
a

[1, 4, 3]

In [21]:
a=[1,2,3]
b=a.copy()
b[1]=4
a

[1, 2, 3]

In [22]:
a=[2,4,5]
b=a.copy()
b

[2, 4, 5]

In [23]:
knights=['we','whom','te','them','we','ask']
knights.index('we')

0

In [24]:
knights.index('ask')

5

In [26]:
numbers=[1,2,3,4,5,6,7,8,9]
numbers.insert(9,'ten')

In [27]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 'ten']

In [29]:
numbers=[1,2,3,4,5,6,7,8]
numbers.insert(4,'four')

In [30]:
numbers

[1, 2, 3, 4, 'four', 5, 6, 7, 8]

In [31]:
x=[1,2,3]
x.pop()
x

[1, 2]

In [32]:
x.pop()

2

In [33]:
x.pop()

1

In [35]:
x=['to','be','them','hee','then','be']
x.remove('be')

In [36]:
x

['to', 'them', 'hee', 'then', 'be']

In [37]:
x.remove("hee")
x

['to', 'them', 'then', 'be']

In [39]:
x=['s','a','n','j','e','e','v','i','n','i']
x.reverse()
x

['i', 'n', 'i', 'v', 'e', 'e', 'j', 'n', 'a', 's']

In [40]:
x.sort()

In [41]:
x

['a', 'e', 'e', 'i', 'i', 'j', 'n', 'n', 's', 'v']

In [42]:
2+2

4

In [43]:
1/2

0.5

In [44]:
1//2

0

In [45]:
1%2

1

In [46]:
10/3

3.3333333333333335

In [47]:
10%3

1

In [48]:
2.75%0.5

0.25

In [49]:
2 ** 3

8

In [50]:
(-3) ** 2

9

In [51]:
width=15
height=5*9
width*height

675

In [52]:
age=input("enter age:")

enter age:22


In [53]:
type(age)

str

In [54]:
age_avg=26
int(age)-age_avg

-4

In [55]:
pow(2,3)

8

In [56]:
10+pow(2,3*5)/3.0

10932.666666666666

In [57]:
abs(-10)

10

In [58]:
abs(-10)

10

In [59]:
abs(10)

10

In [60]:
round(1.0/2.0)

0

In [61]:
import math
math.floor(32.89)

32

In [62]:
from math import sqrt
sqrt(9)

3.0

In [63]:
import cmath
cmath.sqrt(-1)

1j

In [64]:
(1+3j) * (9+4j)

(-3+31j)

In [65]:
"hello,world"

'hello,world'

In [69]:
'let\'s go!'

"let's go!"

In [70]:
'deosn\'t it'

"deosn't it"

In [71]:
x="hello,"
y='world!'

In [72]:
x+y

'hello,world!'

In [73]:
word='python'

In [74]:
word[0]

'p'

In [76]:
word[4]

'o'

In [77]:
word[-1]

'n'

In [78]:
word[-2]

'o'

In [79]:
word[0]

'p'

In [80]:
word[4]

'o'

In [81]:
word[:2]+word[2:]

'python'

In [82]:
word[:4]+word[4:]

'python'

In [84]:
word=['python']

In [85]:
word

['python']

In [86]:
word[0]='j'

In [87]:
word

['j']

In [88]:
word=['python']
word[0]=['j']

In [89]:
word

[['j']]

In [91]:
word=['python']
word

['python']

In [92]:
word[0]='j'

In [93]:
word

['j']

In [94]:
'j'+word[1:]

TypeError: can only concatenate str (not "list") to str

In [95]:
format="hello,%s.%s enough for ya?"
values=('world','hot')
print(format % values)

hello,world.hot enough for ya?


In [96]:
print('floating point numbers:%5.2f' %(10.144))

floating point numbers:10.14


In [100]:
print('floating point numbers:%32.23f' %(11.123))

floating point numbers:      11.12299999999999933208983


In [101]:
format="pi with three decimals:%3f"

In [102]:
from math import pi

In [103]:
print(format % pi)

pi with three decimals:3.141593


In [105]:
print('first:%s,second:%5.2f,third:%r' %('hi',3.142,'bye'))

first:hi,second: 3.14,third:'bye'


In [107]:
print('first:%s,second:%3.2f,third:%r' %('hello',3.167,'good evening'))

first:hello,second:3.17,third:'good evening'


In [108]:
print('this is a string with an{}'.format('insert'))

this is a string with aninsert


In [109]:
print('the {2}{1}{0}'.format('fox','brown','quick'))

the quickbrownfox


In [110]:
print('first object:{c},second object:{b},third object:{c}'.format(a=1,b='two',c=12.3))

first object:12.3,second object:two,third object:12.3


In [116]:
print('a1:{a},b1:{b},c1:{c}'.format(a='sanj',b=8,c=5))

a1:sanj,b1:8,c1:5


In [117]:
import numpy as np


In [118]:
my_list=[1,2,3]

In [119]:
my_list

[1, 2, 3]

In [120]:
np.array(my_list)

array([1, 2, 3])

In [122]:
my_matrix=[[1,2,3],[3,5,6],[6,7,8]]
np.array(my_matrix)

array([[1, 2, 3],
       [3, 5, 6],
       [6, 7, 8]])

In [124]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [125]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [126]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [127]:
np.zeros(2)

array([0., 0.])

In [132]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
np.zeros(2)

array([0., 0.])